// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/velour-email/VelourActiveEmail.tsx": () => import("../components/mockups/velour-email/VelourActiveEmail.tsx")
};
